gestor/urls.py
from django.urls import path
from gestor.apps.cliente import views as cliente
from gestor.apps.proveedor import views as proveedor
from gestor.apps.contable.cuenta import views as cuenta
from gestor.apps.contable.libro_diario import views as libro_diario
from gestor.apps.contable.libro_mayor import views as libro_mayor
from gestor.apps.estadistica import views as estadistica
from gestor.apps.inventario import views as inventario
from gestor.apps.producto import views as producto
from gestor.apps.usuario import views as usuario
from gestor.apps.factura import views as factura
from gestor import views

urlpatterns = [
    path('', views.menu_principal, name='Menu_principal'),
    path('get_chart/', estadistica.get_chart, name='get_chart'),
    path('get_chart2/', estadistica.get_chart2, name='get_chart2'),

    path('cerrar_secion/', views.cerrar_secion, name='cerrar_secion'),
    path('crear_user/', usuario.crear_user, name='crear_user'),
    path('listar_user/', usuario.listar_user, name='listar_user'),
    path('modificar_user/', usuario.modificar_user, name='modificar_user'),
    path('modificar_user_final/', usuario.modificar_user_final,
         name='modificar_user_final'),
    path('eliminar_user/', usuario.eliminar_user, name='eliminar_user'),

    path('facturar/', factura.facturar, name='facturas'),
    path('generar_factura/', factura.create_factura, name='Create_factura'),
    path('delete_factura/', factura.delete_factura, name='delete_factura'),
    path('anular_factura/<int:factura_id>/', factura.anular_factura, name='anular_factura'),

    path('carga_factura_detalle/', factura.cargar_factura_detalle, name='factura_detalle'),
    path('menu_factura_detalle/', factura.menu_factura_detalle,
         name='menu_factura_detalle'),

    path('finalizar_factura/', factura.finalizar_factura, name='finalizar_factura'),
    path('listar_factura/', factura.listar_factura, name='listar_factura'),
    path('imprimir_factura/', factura.imprimir_factura, name='imprimir_factura'),

    path('cancelar_factura/<int:factura_cabecera_id>/',
         factura.cancelar_factura, name='cancelar_factura'),
    #path('factura_libro/<int:factura_cabecera_id>/', factura.factura_libro, name='factura_libro'),

    path('menu_proveedor/', proveedor.menu_proveedor, name='menu_proveedor'),
    path('carga_proveedor/', proveedor.carga_proveedor, name='carga_proveedor'),
    path('modificar_proveedor/', proveedor.modificar_proveedor, name='modificar_proveedor'),

    path('menu_cliente/', cliente.menu_cliente, name='menu_cliente'),
    path('carga_cliente/', cliente.carga_cliente, name='carga_cliente'),
    path('modificar_cliente/', cliente.modificar_cliente, name='modificar_cliente'),

    path('menproduc/', producto.menu_producto, name='menu_producto'),
    path('producto/', producto.create_product, name='cargar_roducto'),
    path('listar_productos/', producto.listar_productos, name='listar_productos'),
    path('anular_producto/<int:producto_id>/', producto.anular_producto, name='anular_producto'),
    path('modificar_producto/', producto.modificar_producto, name='modificar_producto'),

    path('stock/', inventario.StockListView, name='stock_list'),
    path('menu_iventario/', inventario.menu_iventario, name='menu_iventario'),
    path('cargar_inventario/', inventario.cargar_inventario, name='cargar_inventario'),

    path('menu_libro_diario/', libro_diario.menu_libro_diario, name='Asistencia_contable'),
    path('cargar_libro_diario/', libro_diario.cargar_libro_diario, name='cargar_libro_diario'),
    path('modif_libro_diario/', libro_diario.modificar_libro_diario,
         name='modificar_libro_diario'),

    path('menu_libro_mayor/', libro_mayor.menu_libro_mayor, name='menu_libro_mayor'),
    path('cargar_libro_mayor/', libro_mayor.cargar_libro_mayor, name='cargar_libro_mayor'),
    path('modif_libro_mayor/', libro_mayor.modificar_libro_mayor,
         name='modificar_libro_mayor'),

    path('menu_cuenta/', cuenta.menu_cuenta, name='menu_cuenta'),
    path('registrar_cuenta/', cuenta.registrar_cuenta, name='registrar_cuenta'),
    path('modificar_cuenta/', cuenta.modificar_cuenta, name='modificar_cuenta'),

    path('descargar_libro_mayor/', libro_mayor.descargar_libro_mayor,
         name='descargar_libro_mayor'),
    path('descagar_libro/', libro_diario.descargar_libro, name='descargar_libro'),
    #path('migrar_asientos/', libro_diario.migrar_asientos, name='migrar_asientos'),

    path('mod_libro_diario/', libro_diario.mod_libro_diario, name='mod_libro_diario'),

]

proyecto/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gestor.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

gestor/apps/cliente/models.py
from django.db import models
from gestor.apps.estado.models import estado


class cliente(models.Model):
    nombre = models.CharField(max_length=50, null=True)
    apellido = models.CharField(max_length=50, null=True)
    razon_social = models.CharField(max_length=100, null=False)
    RUC = models.CharField(max_length=12, null=False)
    direccion = models.CharField(max_length=150, null=True)
    correo = models.CharField(max_length=50, null=True)
    num_telefono = models.CharField(max_length=12, null=True)
    estado = models.ForeignKey(estado, on_delete=models.CASCADE)

    def __str__(self):
        return self.RUC

gestor/apps/contable/cuenta/models.py
from django.db import models

class cuenta(models.Model):
    num_cuenta = models.CharField(max_length=50, null=False)
    descripcion = models.CharField(max_length=100, null=False)
    saldo = models.IntegerField()

    def __str__(self):
        return self.num_cuenta

gestor/apps/contable/libro_diario/models.py
from django.db import models
from gestor.apps.contable.cuenta.models import cuenta


class libro_diario(models.Model):
    fecha = models.DateField(null=True)
    num_asiento = models.IntegerField()
    concepto = models.CharField(max_length=200, null=True)

    def __str__(self):
        return f"Asiento {self.num_asiento} - Fecha: {self.fecha}"


class detalle_libro_diario(models.Model):
    num_asiento = models.ForeignKey(libro_diario, on_delete=models.CASCADE)
    concepto = models.CharField(max_length=200, null=False)
    num_cuenta = models.ForeignKey(cuenta, on_delete=models.CASCADE)
    debe = models.IntegerField()
    haber = models.IntegerField()

    def __str__(self):
        return self.num_asiento

    def to_dict(self):
        return {
            "num_asiento": {
                "concepto": self.num_asiento.concepto,
                "num_asiento": self.num_asiento.num_asiento
            },
            "concepto": self.concepto,
            "num_cuenta": {
                "num_cuenta": self.num_cuenta.num_cuenta,
                "descripcion": self.num_cuenta.descripcion
            },
            "debe": self.debe,
            "haber": self.haber
        }

gestor/apps/contable/libro_mayor/models.py
from django.db import models
from gestor.apps.contable.cuenta.models import cuenta


class libro_mayor(models.Model):
    fecha = models.DateField()
    num_asiento = models.IntegerField()
    concepto = models.CharField(max_length=200, null=False)
    num_cuenta = models.ForeignKey(cuenta, on_delete=models.CASCADE)
    debe = models.IntegerField()
    haber = models.IntegerField()
    saldo = models.IntegerField()

    def __str__(self):
        return self.num_asiento

    def __str__(self):
        return self.saldo

    def __str__(self):
        return self.num_cuenta

gestor/apps/estadistica/models.py
from django.db import models

# Create your models here.

gestor/apps/estado/models.py
import datetime
from django.db import models


class estado(models.Model):
    estado = models.CharField(max_length=10)

    def __str__(self):
        return self.estado

gestor/apps/cliente/views.py
from pyexpat.errors import messages
from django.shortcuts import render,  redirect
from .models import (cliente)
from gestor.apps.estado.models import estado as Estados
from gestor.apps.usuario.models import (Role, CustomUser)
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from gestor.decorators import vendedor_required


# -------------------------------------------------------------------------------------------------------------------------
#  ---------------------------------Cliente----------------------------------------------------------------------

@login_required
@vendedor_required
def menu_cliente(request):
    user = request.user
    client = cliente.objects.all()

    paginator = Paginator(client, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if user.is_authenticated:
        try:
            custom_user = CustomUser.objects.get(user=user)
            user_role = custom_user.role.name
        except CustomUser.DoesNotExist:
            user_role = "Sin rol asignado"
    else:
        user_role = "Usuario no autenticado"

    return render(request, 'carga_cliente.html', {"clientes": page_obj, 'user_role': user_role, 'user': user})


@login_required
@vendedor_required
def carga_cliente(request):
    est = get_object_or_404(Estados, pk=1)

    existe = cliente.objects.filter(RUC=request.POST['ruc_cliente']).exists()

    if existe:
        messages.error(request, 'El cliente ya esta cargado.')
        return redirect(menu_cliente)

    else:
        client = cliente(RUC=request.POST['ruc_cliente'], nombre=request.POST['nombre_cliente'], razon_social=request.POST['razon_social'],
                         direccion=request.POST['direccion_cliente'], correo=request.POST['correo_cliente'], estado=est, num_telefono=request.POST['num_telefono'],)
        client.save()

        messages.success(request, 'Cliente guardado!!')
        return redirect(menu_cliente)


@login_required
@vendedor_required
def modificar_cliente(request):
    id_cliente = request.POST['id_cliente']

    existe = cliente.objects.filter(id=request.POST['id_cliente']).exists()

    if existe:
        est = Estados.objects.filter(
            id=request.POST['estado_cliente'+id_cliente]).exists()

        aux_cliente = get_object_or_404(cliente, pk=request.POST['id_cliente'])

        aux_cliente.RUC = request.POST['ruc_cliente'+id_cliente]
        aux_cliente.nombre = request.POST['nom_cuenta'+id_cliente]
        aux_cliente.razon_social = request.POST['razon_social'+id_cliente]
        aux_cliente.direccion = request.POST['direccion_cliente'+id_cliente]
        aux_cliente.correo = request.POST['correo_cliente'+id_cliente]
        aux_cliente.num_telefono = request.POST['num_telefono'+id_cliente]

        if est:
            est = get_object_or_404(
                Estados, id=request.POST['estado_cliente'+id_cliente])
            aux_cliente.estado = est

        aux_cliente.save()

        messages.success(request, 'Cliente actualizado!!')
        return redirect(menu_cliente)
    else:
        messages.error(request, 'Cliente no existe!!')
        return redirect(menu_cliente)

gestor/apps/contable/cuenta/views.py
from datetime import date
from pyexpat.errors import messages
from django.shortcuts import render,  redirect
from .models import (cuenta)
from gestor.apps.usuario.models import (Role, CustomUser)
from django.shortcuts import get_object_or_404
from django.core.paginator import Paginator, Page
from django.views.decorators.cache import never_cache
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from gestor.decorators import admin_required, vendedor_required, contador_required


# ----------------------------------------------------------------------------------------------------------------------
#  ---------------------------------Cuentas----------------------------------------------------------------------

@never_cache
@login_required
@contador_required
def menu_cuenta(request):
    user = request.user
    cuentas = cuenta.objects.all().order_by('id')

    paginator = Paginator(cuentas, 10)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if user.is_authenticated:
        try:
            custom_user = CustomUser.objects.get(user=user)
            user_role = custom_user.role.name
        except CustomUser.DoesNotExist:
            user_role = "Sin rol asignado"
    else:
        user_role = "Usuario no autenticado"

    return render(request, 'carga_cuenta.html', {"cuentas": page_obj, 'user_role': user_role, 'user': user})


@never_cache
@login_required
@contador_required
def registrar_cuenta(request):
    fecha_hoy = date.today()

    existe = cuenta.objects.filter(
        num_cuenta=request.POST['num_cuenta']).exists()

    if existe:
        messages.error(request, 'Cuenta ya existe!!')
        return redirect(menu_cuenta)

    else:
        cta = cuenta(num_cuenta=request.POST['num_cuenta'],
                     descripcion=request.POST['nom_cuenta'], saldo=0)
        cta.save()

        messages.success(request, 'Cuenta guardada!!')
        return redirect(menu_cuenta)


@never_cache
@login_required
@contador_required
def modificar_cuenta(request):
    id_cuenta = request.POST['id_cuenta']

    existe = cuenta.objects.filter(id=request.POST['id_cuenta']).exists()

    if existe:
        aux_cuenta = get_object_or_404(cuenta, pk=request.POST['id_cuenta'])

        aux_cuenta.num_cuenta = request.POST['num_cuenta'+id_cuenta]
        aux_cuenta.descripcion = request.POST['nom_cuenta'+id_cuenta]
        aux_cuenta.saldo = request.POST['id_monto'+id_cuenta]

        aux_cuenta.save()

        messages.success(request, 'Cuenta actualizada!!')
        return redirect(menu_cuenta)
    else:
        messages.error(request, 'Cuenta no existe!!')

        return redirect(menu_cuenta)

gestor/apps/estadistica/views.py
from urllib.parse import urlencode
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render,  redirect
from gestor.apps.contable.libro_diario.models import cuenta, libro_diario, detalle_libro_diario
from gestor.apps.producto.models import (producto)
from gestor.apps.inventario.models import (inventario)
from gestor.apps.contable.libro_mayor.models import (libro_mayor)
from django.views.decorators.cache import never_cache


def get_chart(request):
    produc = producto.objects.all()

    chart = {
        'tooltip': {
            'show': True,
            'trigger': "axis",
            'triggerOn': "mousemove|click"
        },
        'xAxis': [
            {
                'type': "category",
                'data': []
            }
        ],
        'yAxis': [
            {
                'type': "value"
            }
        ],
        'series': []
    }

    colors = ['blue', 'orange', 'red', 'black', 'yellow',
              'green', 'magenta', 'lightblue', 'purple', 'brown']

    for idx, p in enumerate(produc):
        fecha_labels = []
        fecha_labels_aux = []
        stock_accumulative = []
        current_stock = 0

        linea = inventario.objects.filter(cod_producto=p).order_by('fecha')
        for l in linea:
            fecha_labels.append(l.fecha.strftime('%Y-%m-%d'))
            fecha_labels_aux.append(l.fecha.strftime('%Y-%m-%d'))
            if l.tipo_movimiento:
                current_stock += l.cantidad
            else:
                current_stock -= l.cantidad
            stock_accumulative.append(current_stock)

        random_color = colors[idx % len(colors)]

        chart['series'].append({
            'name': p.descripcion,
            'data': stock_accumulative,
            'type': "line",
            'itemStyle': {'color': random_color},
        })

        # Asegúrate de que todas las series tengan la misma fecha_labels (eje X)
        chart['xAxis'][0]['data'] = fecha_labels_aux

    return JsonResponse(chart)


@never_cache
def get_chart2(request):
    produc = cuenta.objects.all()

    chart1 = {
        'tooltip': {
            'show': True,
            'trigger': "axis",
            'triggerOn': "mousemove|click"
        },
        'xAxis': [
            {
                'type': "category",
                'data': []
            }
        ],
        'yAxis': [
            {
                'type': "value"
            }
        ],
        'series': []
    }

    colors = ['blue', 'orange', 'red', 'black', 'yellow',
              'green', 'magenta', 'lightblue', 'purple', 'brown']

    for idx, p in enumerate(produc):
        fecha_labels = []
        fecha_labels_aux = []
        stock_accumulative = []
        current_stock = 0

        linea = libro_mayor.objects.filter(num_cuenta=p).order_by('fecha')
        for l in linea:
            fecha_labels.append(l.fecha.strftime('%Y-%m-%d'))
            fecha_labels_aux.append(l.fecha.strftime('%Y-%m-%d'))
            current_stock += l.debe
            current_stock += l.haber
            stock_accumulative.append(current_stock)

        random_color = colors[idx % len(colors)]

        chart1['series'].append({
            'name': p.descripcion,
            'data': stock_accumulative,
            'type': 'bar',
            'seriesLayoutBy': 'row',
            'emphasis': {
                'focus': 'series'
            },
            'itemStyle': {'color': random_color},
        })

        # Asegúrate de que todas las series tengan la misma fecha_labels (eje X)
        chart1['xAxis'][0]['data'] = fecha_labels_aux

    return JsonResponse(chart1)
 

gestor/apps/estado/views.py
from django.shortcuts import render

# Create your views here.

gestor/templates/cargar_asiento_diario.html
{% extends "Base.html" %} {% load static %}
<head>
  <title>{% block title %} Libro Diario {% endblock %}</title>
</head>
<body>
  {% block content %}

  <div class="container">
    <div class="col-md-12">
      <h1 class="display-6">Libro diario</h1>

      <div class="card card-body bg-secondary">
        <div class="card card-body bg-dark mb-2">
          <div class="row g-3 mb-2">
            <div class="col-md-12">
              <h2 class="form-label">Ingrese datos del asiento</h2>
            </div>
            <div class="col-md-12">
              <h6 class="form-label">Cabecera del asiento</h6>
            </div>

            <form id="dataForm" class="row" autocomplete="off">
              {% csrf_token %}

              <div class="col-md-3">
                <input
                  type="date"
                  class="form-control"
                  id="fecha_emision"
                  name="fecha_emision"
                  required
                />
              </div>
              <div class="col-md-6 mb-2">
                <input
                  type="text"
                  class="form-control"
                  id="id_concepto"
                  name="id_concepto"
                  placeholder="Concepto"
                  required
                />
              </div>

              <div class="card card-body bg-secondary mb-2">
                <div class="row">
                  <div class="col-md-12">
                    <h6 class="form-label">Detalle del asiento:</h6>
                  </div>
                  <div class="col-md-2">
                    <select
                      id="num_cuenta"
                      class="form-select"
                      name="num_cuenta"
                      required
                    >
                      <option selected disabled value>Cuenta</option>
                      {% for cuenta in cuentas %}
                      <option
                        value="{{cuenta.num_cuenta}}, {{cuenta.descripcion}}"
                      >
                        {{cuenta.descripcion}}
                      </option>
                      {% empty %}
                      <h4 class="text-center">No hay cuenta</h4>
                      {% endfor %}
                    </select>
                  </div>
                  <div class="col-md-3">
                    <select
                      id="tipo_movimiento"
                      class="form-select"
                      name="tipo_movimiento"
                      required
                    >
                      <option selected disabled value>Tipo movimiento</option>
                      <option value="1">Debe</option>
                      <option value="2">Haber</option>
                    </select>
                  </div>
                  <div class="col-md-4">
                    <div class="input-group">
                      <input
                        type="number"
                        class="form-control"
                        id="id_monto"
                        name="id_monto"
                        placeholder="Ingrese monto del movimiento"
                        required
                      />
                      <span class="input-group-text">G</span>
                    </div>
                  </div>
                  <div class="col-md-3">
                    <input
                      type="submit"
                      class="form-control"
                      value="Agregar al asiento"
                    />
                  </div>
                </div>
              </div>
            </form>

            <form
              id="fromu"
              action="{% url 'cargar_libro_diario' %}"
              method="POST"
              autocomplete="off"
            >
              <input
                type="hidden"
                id="fecha_emision_hidden"
                name="fecha_emision_hidden"
              />
              <input type="hidden" name="concepto" id="concepto-hidden" />
              <input type="hidden" name="cuenta" id="cuenta-hidden" />
              <input type="hidden" name="debe" id="debe-hidden" />
              <input type="hidden" name="haber" id="haber-hidden" />

              {% csrf_token %}

              <table
                id="tablaDatos"
                name="tablaDatos"
                class="table table-striped table-bordered bordered-dark table-secondary"
              >
                <tr>
                  <th scope="col" style="width: 42%">Concepto.</th>
                  <th scope="col" style="width: 8%">Cta.</th>
                  <th scope="col" style="width: 20%">Descrip.</th>
                  <th scope="col" style="width: 12%">Debe</th>
                  <th scope="col" style="width: 12%">Haber</th>
                  <th scope="col" style="width: 12%">Option</th>
                </tr>
              </table>

              <div class="row g-3 mb-2">
                <div class="col-3">
                  <h5>Diferencia de Debe y haber</h5>
                </div>
                <div class="col-3">
                  <input
                    id="tdiferencia"
                    name="tdiferencia"
                    class="form-control"
                    value="0"
                    type="text"
                    style="float: left"
                    readonly=""
                  />
                </div>
                <div class="col-5">
                  <button
                    id="agregarAsientoButton"
                    type="submit"
                    class="btn btn-success"
                  >
                    Grabar asiento
                  </button>
                </div>
              </div>
            </form>

            <div class="col-12">
              {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                <li
                  class="{% if message.tags == 'error' %}alert alert-danger {% elif message.tags == 'success' %}alert alert-success{% endif %}"
                  role="alert"
                >
                  {{ message }}
                </li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
          </div>
        </div>

        <div class="col-12">
          <table
            class="table table-info table-striped table-bordered border-dark"
          >
            <thead>
              <tr>
                <th scope="col" style="width: 14%">fecha</th>
                <th scope="col" style="width: 0%">Asiento</th>
                <th scope="col" style="width: 55%">Concepto.</th>
                <th scope="col" style="width: 12%">Option</th>
              </tr>
            </thead>
            <tbody>
              {% for libro in libros_diarios %}
              <tr>
                <td>{{ libro.fecha|date:'Y-m-d' }}</td>
                <td>{{libro.num_asiento}}</td>
                <td>{{libro.concepto}}</td>
                <td>
                  <form
                    action="{% url 'mod_libro_diario' %}"
                    method="POST"
                    autocomplete="off"
                  >
                    {% csrf_token %}
                    <button
                      class="btn btn-sm btn-primary"
                      name="id_libro"
                      value="{{libro.id}}"
                    >
                      <i class="fa fa-solid fa-pencil"></i>
                    </button>
                  </form>
                </td>
              </tr>
              {% empty %}
              <td colspan="7">
                <h3 class="text-center">No hay asientos cargados</h3>
              </td>
              {% endfor %}
            </tbody>
          </table>

          <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
              {% if libros_diarios.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1">&laquo; first</a>
              </li>
              <li class="page-item">
                <a
                  class="page-link"
                  href="?page={{libros_diarios.previous_page_number}}"
                  >previous</a
                >
              </li>
              {% endif %}

              <li class="page-item disabled">
                <span class="page-link"
                  >Page {{ libros_diarios.number }} of
                  {{libros_diarios.paginator.num_pages}}</span
                >
              </li>

              {% if libros_diarios.has_next %}
              <li class="page-item">
                <a
                  class="page-link"
                  href="?page={{ libros_diarios.next_page_number }}"
                  >next</a
                >
              </li>
              <li class="page-item">
                <a
                  class="page-link"
                  href="?page={{ libros_diarios.paginator.num_pages }}"
                  >last &raquo;</a
                >
              </li>
              {% endif %}
            </ul>
          </nav>
        </div>

        <form action="{% url 'descargar_libro' %}" method="POST">
          {% csrf_token %}

          <div class="row">
            <div class="col-12 mb-2">
              <a class="btn btn-primary" href="{% url 'migrar_asientos' %}"
                >Migrar</a
              >
            </div>
            <div class="col-2">
              <input
                type="text"
                class="form-control"
                id="fecha_deseada"
                name="fecha_deseada"
                placeholder="AAAA-MM o AAAA"
                required
              />
            </div>
            <div class="col-4">
              <button class="btn btn-primary">Descargar libro</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <script src="{% static 'js/agregar-asiento.js' %}"></script>

  {% endblock %}
</body>

gestor/templates/crear_user.html
{% extends "Base.html" %} {% load static %}
<head>
  <title>{% block title %} Create users {% endblock %}</title>
</head>
<body>
  {% block content %}

  <div class="container">
    <div class="col-md-7 offset-md-2 mb-2 mt-5">
      <h1 class="display-6">Usuario</h1>

      <div class="card card-body bg-secondary">
        <form method="post">
          {% csrf_token %}

          <div class="row g-2">
            <div class="col-md-3 mb-2">
              <label for="username">User:</label>
              <input
                type="text"
                name="username"
                class="form-control"
                placeholder="username"
                required
              />
            </div>
            <div class="col-md-4 offset-md-1">
              <label for="nombre">Nombre:</label>
              <input
                type="text"
                name="nombre"
                class="form-control"
                placeholder="Fulano"
                required
              />
            </div>
            <div class="col-md-4">
              <label for="apellido">Apellido:</label>
              <input
                type="text"
                name="apellido"
                class="form-control"
                placeholder="De Tal"
                required
              />
            </div>

            <div class="col-12">
              <label for="password1">Contraseña:</label>
            </div>
            <div class="col-md-4 mb-2">
              <input
                type="password"
                name="password1"
                id="password1"
                class="form-control"
                placeholder="password"
              />
            </div>
            <div class="col-md-4">
              <input
                type="password"
                name="password2"
                id="password2"
                class="form-control"
                placeholder="confirm password"
              />
            </div>

            <div class="col-md-5">
              <label for="email">Corre:</label>
              <input
                type="email"
                name="email"
                class="form-control"
                placeholder="test@example.com"
              />
            </div>
            <div class="col-md-4 mb-2">
              <label for="rols">Rol del usaurio:</label>
              <select id="rols" class="form-select" name="rols" required>
                {% for rol in rols %}
                <option value="{{rol.name}}">{{rol.name}}</option>
                {% endfor %}
              </select>
            </div>

            <div class="col-12 d-grid mb-3">
              <button class="btn btn-success">Crear</button>
            </div>

            <div class="mb-12">
              {% if messages %}
              <ul class="messages">
                {% for message in messages %}
                <li
                  class="{% if message.tags == 'error' %}alert alert-danger {% elif message.tags == 'success' %}alert alert-success{% endif %}"
                  role="alert"
                >
                  {{ message }}
                </li>
                {% endfor %}
              </ul>
              {% endif %}
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  {% endblock %}
</body>